---
title: "INTRODUÇÃO À ECONOMIA (ECN001)"
author: "Prof. Victor Valerio"
date: "Última Atualização: `r Sys.Date()`"
output:
  rmdformats::material:
    highlight: kate
---


```{css, echo = FALSE}

.header-panel {
    background-color: #22b676;
    min-height: 144px;
    position: relative;
    z-index: 3;
}


a, a:focus, a:hover {
    color: #22b676;
}

.pages h1 {
    color: #22b676;
}

.pages h2 {
    color: #22b676;
}

.menu ul li a {
    color: #22b676;
    text-decoration: none;
}

```


<div style="text-align: justify">

# 01 - MÉTODO DE PESQUISA EM ECONOMIA


## Objetivo da Aula


Esta aula foi estruturada com a finalidade de realizar uma apresentação sobre o método de pesquisa 
em economia, correspondendo à segunda aula de Introdução à Economia (ECN001) ao longo do primeiro 
semestre de 2021 na Universidade Federal de Itajubá (no âmbito do Regime de Tratamento 
Excepcional - RTE).


## Principais Conceitos


Para atender ao objetivo traçado são realizadas uma série de definições introdutórias sobre o tema, 
podendo se destacar os seguintes conceitos:


- **Modelo Hipotético-Dedutivo**;

- **Economia Positiva**;

- **Economia Normativa**.


## Disponibilização de Materiais


- [**VIDEOAULA - MÉTODO DE PESQUISA EM ECONOMIA**](https://www.youtube.com/watch?v=fQg66Daz3cQ);


- [**SLIDES**](https://1drv.ms/p/s!At0yTgXpzJkLguIwJS9YxyEktlTcVg?e=cDmrbs)


# 01 - PREFERÊNCIAS DO CONSUMIDOR


## Objetivo da Aula

Esta aula têm por objetivo geral fornecer ao estudante um primeiro contato com a modelagem econômica,
mais especificamente, serão estruturados os conceitos base para representação das decisões de consumo
de um indivíduo. 


## Principais Conceitos

Para atender aos objetivos traçados são realizadas uma série de definições introdutórias sobre o tema,
podendo se destacar os conceitos:

- **Cesta de Bens**; 

- **Axiomas de Racionalidade**; 

- **Notação de Preferências**; 

- **Preferências Reflexivas**; 

- **Preferências Completas**; 

- **Preferências Monotônicas**; 

- **Preferências Transitivas**; 

- **Utilidade e Funções Utilidade**; 

- **Utilidade Marginal**.


## Disponibilização de Materiais


- [**VIDEOAULA - PREFERÊNCIAS DO CONSUMIDOR**](https://www.youtube.com/watch?v=NrToSmAUmmc);


- [**SLIDES - PARTE 1**](https://1drv.ms/p/s!At0yTgXpzJkLgtd0Sc344b3a8wvLlQ?e=JLfM3M)


# 03 - FUNÇÕES UTILIDADE E ESCOLHA ÓTIMA


## Objetivo da Aula

Esta aula têm por objetivo geral fornecer ao estudante um primeiro contato com a modelagem econômica,
mais especificamente, serão estruturados os conceitos base para representação das decisões de consumo
de um indivíduo. 


## Principais Conceitos

Para atender aos objetivos traçados são realizadas uma série de definições introdutórias sobre o tema,
podendo se destacar os conceitos:


- **Função Utilidade Composta**;

- **Utilidades Marginais**;

- **Curvas de Indiferença**;

- **Taxa Marginal de Substituição**;

- **Funções Utilidade (propriedades especiais)**;

- **Restrição Orçamentária**;

- **Escolha Ótima**.


## Disponibilização de Materiais


- [**VIDEOAULA - ESCOLHA ÓTIMA**](https://youtu.be/WITsxKUOBgE);


- [**SLIDES - PARTE 1**](https://onedrive.live.com/view.aspx?resid=B99CCE9054E32DD!44520&ithint=file%2cpptx&authkey=!AHN-nRYsKtD7ZjA)


- [**SLIDES -  PARTE 2**](https://onedrive.live.com/view.aspx?resid=B99CCE9054E32DD!44521&ithint=file%2cpptx&authkey=!AAwps5HBc3Hbh2w)


# 04 - OTIMIZAÇÃO DA PRODUÇÃO (CURTO PRAZO)


## Objetivo da Aula

Esta aula têm por objetivo geral realizar as definições necessárias para  compreensão do segundo 
modelo microeconômico (produção ótima no curto prazo). 


## Principais Conceitos

Para atender aos objetivos traçados são realizadas uma série de definições introdutórias sobre o tema,
podendo se destacar os conceitos:

- **Processo de Produção**;

- **Fatores de Produção (Trabalho e Capital)**;

- **Função de Produção (diferença ente curto e longo prazo)**;

- **Indicadores de Desempenho**; 

- **Produto Marginal do Trabalho**;

- **Produto Médio do Trabalho**;

- **Estratégia Ótima de Curto Prazo**.


## Disponibilização de Materiais


- [**VIDEOAULA - OTIMIZAÇÃO DA PRODUÇÃO (CURTO PRAZO)**](https://youtu.be/tKEHhDBuLIs);


- [**SLIDES**](https://1drv.ms/p/s!At0yTgXpzJkLgt0-5ks8ETv7nt0D3g?e=7BGLAG)


# 05 - OTIMIZAÇÃO DA PRODUÇÃO (LONGO PRAZO)


## Objetivo da Aula

Esta aula têm por objetivo geral realizar as definições necessárias para  compreensão do segundo 
modelo microeconômico (produção ótima no curto prazo). 


## Principais Conceitos

Para atender aos objetivos traçados são realizadas uma série de definições introdutórias sobre o tema,
podendo se destacar os conceitos:

- **Função de Produção Composta**;

- **Produtos Marginais dos Fatores de Produção (Trabalho e Capital)**;

- **Isoquantas**;

- **Taxa Marginal de Substituição Técnica**; 

- **Custo Total**;

- **Estratégia Ótima de Longo Prazo**.


## Disponibilização de Materiais


- [**VIDEOAULA - OTIMIZAÇÃO DA PRODUÇÃO (LONGO PRAZO)**](https://www.youtube.com/watch?v=XuCkKgMojpk);


- [**SLIDES**](https://1drv.ms/p/s!At0yTgXpzJkLgvIpGzwi-LAO4xPMfA?e=sgoPos)

# 06 - EQUILÍBRIO DE MERCADO


## Objetivo da Aula

Esta aula têm por objetivo geral realizar as definições necessárias para  compreensão do último
modelo microeconômico (equilíbrio de mercado). 


## Principais Conceitos


Para atender aos objetivos traçados são realizadas uma série de definições introdutórias sobre o tema,
podendo se destacar os conceitos:

- **Definição de Mercado**;

- **Preço e Quantidade**;

- **Lei da Demanda**;

- **Oferta da Oferta**; 

- **Equilíbrio de Mercado**;

- **Excesso de Oferta**;

- **Excesso de Demanda**;

- **Variáveis Endógenas e Exógenas**;

- **Estática Comparativa**.


## Disponibilização de Materiais


- [**VIDEOAULA - EQUILÍBRIO DE MERCADO**](https://www.youtube.com/watch?v=DizEPZr_HJs);


- [**SLIDES**](https://1drv.ms/p/s!At0yTgXpzJkLgvlWC6CgizjenP3UhQ?e=MFsekz)


# 07 - AGREGADOS MACROECONÔMICOS (FLUXO CIRCULAR DA RENDA)


## Objetivo da Aula


Esta aula têm por objetivo geral fornecer ao estudante um primeiro contato com o funcionamento da 
economia de um país, sendo que, este funcionamento da economia de um país é chamado aqui de 
“dinâmica macroeconômica”. 


## Principais Conceitos


Para atender aos objetivos traçados são realizadas uma série de definições introdutórias sobre o 
tema, podendo se destacar os conceitos:

- **Produto Agregado**;

- **Valor Agregado**;

- **Renda Agregada**;

- **Despesa Agregada**;

- **Setores Institucionais (Famílias, Empresas, Governo e Resto do Mundo)**;

- **Residentes e Não Residentes**.


## Disponibilização de Materiais


- [**VIDEOAULA - AGREGADOS MACROECONÔMICOS (FLUXO CIRCULAR DE RENDA)**](https://youtu.be/Suz2oBsnMwE);

- [**SLIDES - A**](https://1drv.ms/p/s!At0yTgXpzJkLg4YyTGPyb7zcLMQGIQ?e=XPArmj)

- [**SLIDES - B**](https://valerio-victor.github.io/03_adm03f_fluxo_circular_renda/#1)

 
# 08 - AGREGADOS MACROECONÔMICOS (CONTABILIDADE SOCIAL)

## Objetivo da Aula


Esta aula têm por objetivo geral aproximar o aluno do estudo prático do funcionamento da economia de
uma país (dinâmica macroeconômica) a partir dos conceitos estruturados no fluxo circular da renda.


## Principais Conceitos


Para atender aos objetivos traçados são realizadas uma série de definições introdutórias sobre o 
tema, podendo se destacar os conceitos:

- **PARTE I**:

  - **Produto Agregado**;

  - **Produto Interno Bruto (PIB)**;

  - **Renda Nacional Bruta (RNB)**;

  - **Renda Líquida Enviada ao Exterior (RLEE)**;

  - **Renda Líquida Recebida do Exterior (RLRE)**;

  - **Transferências Unilaterais Recebidas (TUR)**;

  - **Renda Nacional Disponível Bruta (RNDB)**;

  - **Renda Líquida do Governo (RLG)**;
  
  - **Renda Privada Disponível (RPD)**.
  
- **PARTE II**:

  - **Consumo das Famílias (C)**;

  - **Investimento das Empresas (I)**;

  - **Gastos do Governo (G)**;

  - **Exportações (X)**;

  - **Importações (M)**;

  - **Poupança das Famílias (S)**;

  - **Poupança Pública**;

  - **Poupança do Setor Externo**.


## Disponibilização de Materiais

- **PARTE I**:

- [**VIDEOAULA - AGREGADOS MACROECONÔMICOS (CONTABILIDADE SOCIAL)**](https://youtu.be/a64faeCC8p8).

- **PARTE II**:

- [**VIDEOAULA - AGREGADOS MACROECONÔMICOS (CONTABILIDADE SOCIAL)**](https://youtu.be/JU9SYfXnjz0).

- **PARTE I e PARTE II**:

- [**SLIDES**](https://1drv.ms/p/s!At0yTgXpzJkLgtt1cf5cbVDQkaVaPw?e=C9Zau5).

# 09 - TAXA DE INFLAÇÃO


## Objetivo da Aula


Esta aula têm por objetivo geral fornecer ao estudante um primeiro contato com os índices de preços 
(em especial, IPCA) e com as respectivas relações com as taxas de inflação.


## Principais Conceitos


Para atender aos objetivos traçados são realizadas uma série de definições introdutórias sobre o 
tema, podendo se destacar os conceitos: 


- **Séries Temporais**;

- **Números Índices**;

- **Índices de Preços**;

- **IPCA**;

- **Taxa de Inflação**;

- **Causas e Consequências da Inflação**.



## Disponibilização de Materiais


- [**VIDEOAULA - EQUILÍBRIO DE MERCADO**](https://www.youtube.com/watch?v=WFSFzTvhp8U);


- [**SLIDES**](https://1drv.ms/p/s!At0yTgXpzJkLgt1XVN5nC9MQUJATFA?e=7JOSIu)


# 10 - TAXA DE JUROS

## Objetivo da Aula


Esta aula têm por objetivo geral fornecer ao estudante um primeiro contato com as principais taxas de 
juros (em especial, SELIC e DI) e seus impactos na economia.


## Principais Conceitos


Para atender aos objetivos traçados são realizadas uma série de definições introdutórias sobre o 
tema, podendo se destacar os conceitos: 


- **Capitalização Simples e Capitalização Composta**;

- **Taxa Básica de Juros (SELIC)**;

- **Taxa DI**;

- **SPREAD bancário**;

- **Relação com Inflação**.


## Disponibilização de Materiais


- [**VIDEOAULA - TAXA DE JUROS**](https://youtu.be/yOo2-m9hngI);


- [**SLIDES**](https://1drv.ms/p/s!At0yTgXpzJkLgqZsdMGhAOfVhNTmbw?e=ULvk2i)


# 11 - TAXA DE CÂMBIO


## Objetivo da Aula


Esta aula têm por objetivo geral fornecer ao estudante um primeiro contato com os principais 
conceitos associados à taxa de câmbio e seus impactos na economia.


## Principais Conceitos


Para atender aos objetivos traçados são realizadas uma série de definições introdutórias sobre o 
tema, podendo se destacar os conceitos: 


- **Taxa de Câmbio Nominal**;


- **Relação com Exportações**;


- **Taxa de Câmbio Real**;


- **Relação com Inflação**;


- **Relação com Importações**;


- **Relação com a Competitividade da Indústria Nacional**.


## Disponibilização de Materiais


- [**VIDEOAULA - TAXA DE JUROS**](https://youtu.be/Q03BoeKVgSw);


- [**SLIDES**](https://1drv.ms/p/s!At0yTgXpzJkLg45L6KQfIDEQP-0PwA?e=xzRgVz)








